import { ContentItem, NewsContentItem, RecommendationContentItem, SocialContentItem } from '@/types/content';

export const INITIAL_NEWS_ITEMS: NewsContentItem[] = [
  {
    id: 'news-1',
    type: 'news',
    category: 'technology',
    title: 'Next-Gen Quantum Processors Achieve Practical Error Correction Milestone',
    description: 'Researchers unveiled a fault-tolerant logical qubit system demonstrating computational fidelity exceeding 99.98%, paving the way for commercial quantum utility.',
    source: 'TechSphere Daily',
    author: 'Elena Vance',
    readTimeMinutes: 5,
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1200&q=80',
    isTrending: true,
    trendingRank: 1,
    engagement: { likes: 1420, shares: 382, comments: 194, views: 18400 },
    fullContent: 'In a landmark breakthrough published in Nature Computing, an international consortia of quantum engineers demonstrated real-time topological error correction across 128 physical qubits. The architecture sustains coherence times two orders of magnitude beyond prior benchmarks, promising tangible advancements in molecular simulation and cryptography.',
  },
  {
    id: 'news-2',
    type: 'news',
    category: 'ai',
    title: 'Autonomous Multimodal Agents Begin Handling End-to-End Enterprise Workflows',
    description: 'Autonomous reasoning architectures are moving beyond chat interfaces into active multi-agent orchestrations executing legal, financial, and code deployments.',
    source: 'Synthetica Review',
    author: 'Marcus Chen',
    readTimeMinutes: 4,
    createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    isTrending: true,
    trendingRank: 3,
    engagement: { likes: 2190, shares: 640, comments: 312, views: 24300 },
    fullContent: 'Modern enterprises are rapidly integrating autonomous agents capable of perceiving browser interfaces, databases, and continuous integration pipelines. Benchmarks indicate automated resolution times for code refactoring reduced by 65% across early pilot cohorts.',
  },
  {
    id: 'news-3',
    type: 'news',
    category: 'finance',
    title: 'Global Central Banks Accelerate Interoperable Digital Currency Pilots',
    description: 'A coalition of 14 central financial institutions has completed Phase II of Project Agora, demonstrating instant cross-border settlement with fractional costs.',
    source: 'Global Capital Markets',
    author: 'Aria Sterling',
    readTimeMinutes: 6,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
    engagement: { likes: 870, shares: 190, comments: 88, views: 9800 },
    fullContent: 'Project Agora has transitioned to testing automated compliance rails and atomic DvP (Delivery versus Payment) contracts. The pilot eliminated customary 3-day correspondent banking delays in high-volume foreign currency exchange.',
  },
  {
    id: 'news-4',
    type: 'news',
    category: 'science',
    title: 'James Webb Space Telescope Identifies Atmospheric Carbon on Temperate Exoplanet',
    description: 'Transmission spectroscopy confirms carbon monoxide and methane signatures on exoplanet K2-18b, situated comfortably within the habitable stellar orbit.',
    source: 'AstroPhysical Journal',
    author: 'Dr. Tariq Al-Mansoor',
    readTimeMinutes: 5,
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    engagement: { likes: 3200, shares: 980, comments: 450, views: 41000 },
    fullContent: 'Spectroscopic absorption features recorded across 1 to 5 microns reveal atmospheric composition consistent with an oceanic hycean world. Future observational cycles will assess dimethyl sulfide concentrations to test biological origin hypotheses.',
  },
  {
    id: 'news-5',
    type: 'news',
    category: 'gaming',
    title: 'Next-Gen Neural Rendering Engines Debut Real-Time Path Tracing at 144 FPS',
    description: 'Hardware manufacturers reveal deep neural reconstruction algorithms that interpolate micro-geometry with zero artifacting.',
    source: 'Voxel Horizon',
    author: 'Kai Sorenson',
    readTimeMinutes: 3,
    createdAt: new Date(Date.now() - 1000 * 60 * 260).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    engagement: { likes: 1850, shares: 420, comments: 230, views: 16200 },
    fullContent: 'Neural caching replaces traditional radiance cascades by evaluating continuous spatial embeddings in real-time on dedicated tensor cores, dramatically lowering power consumption while delivering photo-realistic global illumination.',
  },
  {
    id: 'news-6',
    type: 'news',
    category: 'sports',
    title: 'World Athletics Embraces Smart Kinetic Sensors for Millimeter Sprint Judgments',
    description: 'High-speed lidar embedded along running tracks provides instantaneous biomechanical telemetry for fans and judges alike.',
    source: 'Athletic Chronicle',
    author: 'Jordan Miles',
    readTimeMinutes: 4,
    createdAt: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
    engagement: { likes: 620, shares: 110, comments: 45, views: 7600 },
    fullContent: 'Athletes can now review their acceleration gradients, stride frequency, and ground contact times within seconds of crossing the tape, offering spectators an unprecedented tactical view into 100-meter sprints.',
  },
];

export const INITIAL_RECOMMENDATIONS: RecommendationContentItem[] = [
  {
    id: 'rec-1',
    type: 'recommendation',
    subType: 'movie',
    category: 'entertainment',
    title: 'Chronos: The Paradox of Horizon',
    description: 'A gripping speculative sci-fi thriller following a team of astrophysicists discovering a localized temporal vortex beneath the Antarctic shelf.',
    source: 'CineMatch Curator',
    creatorOrArtist: 'Dir. Sarah Lin (Starring David Oyelowo)',
    rating: 9.3,
    releaseYear: 2026,
    duration: '2h 18m',
    createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1200&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isTrending: true,
    trendingRank: 2,
    engagement: { likes: 3400, shares: 890, comments: 420, views: 32000 },
  },
  {
    id: 'rec-2',
    type: 'recommendation',
    subType: 'music',
    category: 'entertainment',
    title: 'Neon Odyssey - Ambient Synthetics LP',
    description: 'Deep synthwave atmospheres blended with organic cello ensembles, engineered specifically for high-focus deep work sessions.',
    source: 'SoundCloud Curated',
    creatorOrArtist: 'Aethelgard & The Synthetica Collective',
    rating: 4.9,
    releaseYear: 2026,
    duration: '48m (10 Tracks)',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    audioPreviewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    engagement: { likes: 1670, shares: 512, comments: 144, views: 18900 },
  },
  {
    id: 'rec-3',
    type: 'recommendation',
    subType: 'series',
    category: 'technology',
    title: 'Silicon Frontier: Season 3',
    description: 'The high-stakes chronicle of the rogue team that engineered the first zero-knowledge decentralized operating system.',
    source: 'StreamFlix Originals',
    creatorOrArtist: 'Showrunner Jonathan Reese',
    rating: 8.9,
    releaseYear: 2026,
    duration: '8 Episodes',
    createdAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=1200&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    engagement: { likes: 2890, shares: 730, comments: 395, views: 28000 },
  },
  {
    id: 'rec-4',
    type: 'recommendation',
    subType: 'movie',
    category: 'lifestyle',
    title: 'The Art of Spatial Living',
    description: 'An architectural documentary exploring minimalist micro-homes in Tokyo, Copenhagen, and Patagonia designed around circular sustainable materials.',
    source: 'DesignCinema',
    creatorOrArtist: 'Dir. Mai Tanaka',
    rating: 8.7,
    releaseYear: 2025,
    duration: '1h 34m',
    createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    engagement: { likes: 1120, shares: 280, comments: 75, views: 11400 },
  },
];

export const INITIAL_SOCIAL_ITEMS: SocialContentItem[] = [
  {
    id: 'social-1',
    type: 'social',
    category: 'ai',
    platform: 'twitter',
    title: 'Why agentic workflows beat raw context window expansion every time 🧵',
    description: 'Context windows give you a giant memory dump, but agents with tool use, structured memory, and self-critique loops solve reasoning failures. Here are 5 real benchmarks.',
    source: 'X / Twitter',
    authorHandle: '@sama_researcher',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    authorVerified: true,
    hashtags: ['#ArtificialIntelligence', '#AgenticAI', '#DevLife', '#MachineLearning'],
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    isTrending: true,
    trendingRank: 4,
    engagement: { likes: 4520, shares: 1380, comments: 512, views: 89000 },
  },
  {
    id: 'social-2',
    type: 'social',
    category: 'technology',
    platform: 'bluesky',
    title: 'Just open-sourced our local-first WebRTC collaboration engine!',
    description: 'Zero servers required for direct P2P state synchronization with conflict-free replicated data types (CRDTs). Runs in web workers with full offline support. Star the repo!',
    source: 'Bluesky',
    authorHandle: '@dev_sophia.bsky.social',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    authorVerified: true,
    hashtags: ['#OpenSource', '#WebDev', '#TypeScript', '#CRDT'],
    createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    engagement: { likes: 2840, shares: 890, comments: 240, views: 42000 },
  },
  {
    id: 'social-3',
    type: 'social',
    category: 'gaming',
    platform: 'instagram',
    title: 'First look at Unreal Engine 6 procedural world generator running on mobile',
    description: 'Rendered in real time on standard handheld devices with full Lumen lighting and dynamic weather cycles. The boundary between console and mobile is officially gone.',
    source: 'Instagram',
    authorHandle: '@renderforge_studios',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    authorVerified: false,
    hashtags: ['#GameDev', '#UnrealEngine', '#MobileGaming', '#CGI'],
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80',
    engagement: { likes: 5890, shares: 1420, comments: 630, views: 67000 },
  },
  {
    id: 'social-4',
    type: 'social',
    category: 'finance',
    platform: 'twitter',
    title: 'The macro shift nobody is talking about: Private credit liquidity pools',
    description: 'As high-yield sovereign debt matures, institutional allocations to algorithmic private credit structures reached $2.1T this quarter. Breakdown attached.',
    source: 'X / Twitter',
    authorHandle: '@macro_zenith',
    authorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80',
    authorVerified: true,
    hashtags: ['#Economics', '#Markets', '#Fintech', '#Liquidity'],
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    engagement: { likes: 1390, shares: 410, comments: 92, views: 23000 },
  },
];

export const ALL_INITIAL_ITEMS: ContentItem[] = [
  ...INITIAL_NEWS_ITEMS,
  ...INITIAL_RECOMMENDATIONS,
  ...INITIAL_SOCIAL_ITEMS,
].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

// Generator for simulated real-time dynamic posts
const DYNAMIC_HEADLINES = [
  {
    title: 'Breakthrough Solid-State Battery Begins Mass Automotive Line Trial',
    desc: 'Automaker consortium verifies 900-mile range with 12-minute rapid charging under extreme weather.',
    cat: 'technology' as const,
    source: 'Energy Pulse',
    img: 'https://images.unsplash.com/photo-1558441719-724d15664188?auto=format&fit=crop&w=1200&q=80',
  },
  {
    title: 'Viral Space Symphony Composed by Orbital Sensors Captivates Millions',
    desc: 'Radio frequency variations recorded from solar winds translated into symphonic synth tracks.',
    cat: 'entertainment' as const,
    source: 'Harmonic Cosmos',
    img: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1200&q=80',
  },
  {
    title: 'Decentralized Identity Protocol Becomes Official Standard for 8 Nations',
    desc: 'Citizens gain cryptographic ownership of academic records, health profiles, and passports.',
    cat: 'ai' as const,
    source: 'CyberGazette',
    img: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
  },
  {
    title: 'Historic Marathon Record Smashed by 42 Seconds with Bio-Tuned Footwear',
    desc: 'Kinetic carbon-fiber plates engineered with micro-pneumatic damping set new world speed records.',
    cat: 'sports' as const,
    source: 'Sprint Tribune',
    img: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=80',
  },
];

export function generateLiveContentItem(index: number): ContentItem {
  const template = DYNAMIC_HEADLINES[index % DYNAMIC_HEADLINES.length];
  const now = new Date().toISOString();
  const id = `live-${Date.now()}-${index}`;

  if (index % 3 === 0) {
    return {
      id,
      type: 'news',
      category: template.cat,
      title: `[FLASH] ${template.title}`,
      description: template.desc,
      source: template.source,
      author: 'Live Wire Dispatch',
      readTimeMinutes: 3,
      createdAt: now,
      imageUrl: template.img,
      isTrending: true,
      engagement: { likes: 120 + index * 14, shares: 45, comments: 22, views: 1800 },
      fullContent: `${template.desc} Developed in collaboration with top academic research institutions, this real-time update marks an accelerated shift in technology adoption.`,
    };
  } else if (index % 3 === 1) {
    return {
      id,
      type: 'social',
      category: template.cat,
      platform: 'twitter',
      title: template.title,
      description: `Incredible developments happening right now: ${template.desc}`,
      source: 'X / Twitter',
      authorHandle: '@technow_live',
      authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
      authorVerified: true,
      hashtags: ['#BreakingNews', '#TechUpdate', '#FutureNow'],
      createdAt: now,
      imageUrl: template.img,
      engagement: { likes: 580, shares: 140, comments: 65, views: 7200 },
    };
  } else {
    return {
      id,
      type: 'recommendation',
      subType: 'music',
      category: template.cat,
      title: template.title,
      description: template.desc,
      source: 'Global Discovery',
      creatorOrArtist: 'Live Audio Ensemble',
      rating: 4.8,
      releaseYear: 2026,
      duration: '3m 45s',
      createdAt: now,
      imageUrl: template.img,
      audioPreviewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
      engagement: { likes: 410, shares: 95, comments: 38, views: 4900 },
    };
  }
}
